from django.utils.translation import ugettext_lazy as _

BANK_ROLE_BUSINESS = "BUSINESS"
BANK_ROLE_TRANS = "TRANS"
BANK_ROLE_INVESTMENT = "INVESTMENT"

BANK_OTHER_CODE = "ZZZ"

BANK_ACCOUNT_ROLES = (
    (BANK_ROLE_BUSINESS, _("Business Account")),
    (BANK_ROLE_TRANS, _("Transaction Account")),
    (BANK_ROLE_INVESTMENT, _("Investment Account")),
)

# Entity bank account types (set according to Hyphen account type table)
ENTITY_BANK_ACCOUNT_TYPE_CHEQUE_CURRENT = "1"
ENTITY_BANK_ACCOUNT_TYPE_SAVINGS = "2"
ENTITY_BANK_ACCOUNT_TYPE_TRANSMISSION = "3"
ENTITY_BANK_ACCOUNT_TYPE_BOND = "4"

ENTITY_BANK_ACCOUNT_TYPES = (
    (ENTITY_BANK_ACCOUNT_TYPE_CHEQUE_CURRENT, _("Cheque/Current Account")),
    (ENTITY_BANK_ACCOUNT_TYPE_SAVINGS, _("Savings Account")),
    (ENTITY_BANK_ACCOUNT_TYPE_TRANSMISSION, _("Transmission Account")),
    (ENTITY_BANK_ACCOUNT_TYPE_BOND, _("Bond Account")),
)

ENTITY_BANK_ACCOUNT_TYPE_DESCRIPTION_MAP = {
    ENTITY_BANK_ACCOUNT_TYPE_CHEQUE_CURRENT: _("Cheque/Current Account"),
    ENTITY_BANK_ACCOUNT_TYPE_SAVINGS: _("Savings Account"),
    ENTITY_BANK_ACCOUNT_TYPE_TRANSMISSION: _("Transmission Account"),
    ENTITY_BANK_ACCOUNT_TYPE_BOND: _("Bond Account"),
}

# Entity bank account states.
ENTITY_BANK_ACCOUNT_STATE_VERIFIED = "VERIFIED"
ENTITY_BANK_ACCOUNT_STATE_VALIDATED = "VALIDATED"
ENTITY_BANK_ACCOUNT_STATE_PENDING = "PENDING"
ENTITY_BANK_ACCOUNT_STATE_UNVERIFIED = "UNVERIFIED"

ENTITY_BANK_ACCOUNT_STATES = (
    (ENTITY_BANK_ACCOUNT_STATE_VERIFIED, _("Verified")),
    (ENTITY_BANK_ACCOUNT_STATE_VALIDATED, _("Validated")),
    (ENTITY_BANK_ACCOUNT_STATE_PENDING, _("Pending Verification")),
    (ENTITY_BANK_ACCOUNT_STATE_UNVERIFIED, _("Unverified")),
)

ENTITY_BANK_ACCOUNT_STATES_DESCRIPTION_MAP = {
    ENTITY_BANK_ACCOUNT_STATE_VERIFIED: _("Verified"),
    ENTITY_BANK_ACCOUNT_STATE_VALIDATED: _("Validated"),
    ENTITY_BANK_ACCOUNT_STATE_PENDING: _("Pending Verification"),
    ENTITY_BANK_ACCOUNT_STATE_UNVERIFIED: _("Unverified"),
}
