swagger: '2.0'

info:
  version: "1.0"
  title: Ledger API
  description:

host: api.ledger-api.com

schemes:
  - https

basePath: /v1.0/

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  AuthToken:
    type: apiKey
    name: AuthToken
    in: header
    description: |
      Here is an example of the **AuthToken** header:
      ```
      AuthToken: 97597b60-fe64-4597-a127-98b6b3679b74
      ```

paths:
  /accounts:
    post:
      description: |
        Creates a new account.
      security:
        - AuthToken: []
      parameters:
        - name: Account
          in: body
          required: true
          description: |
            This parameter contains the account information.
          schema:
            properties:
              name:
                type: string
                description: Detailed name of the account.
              currency:
                type: string
                description: The account's currency.
              internal_type:
                type: string
                description: The account's accounting type e.g. ASSET, LIABILITY, EXPENSE, INCOME
      responses:
        200:
          description: Successfully created a account.
          schema:
            properties:
              message:
                type: string
                default: The account was created.
        400:
          description: There are errors with the given parameters.
          schema:
            properties:
              name:
                type: array
                items:
                  type: string
                  default: A valid name is required.
              currency:
                type: array
                items:
                  type: string
                  default: A valid currency is required.
        403:
          description: The account already exits.
          schema:
            properties:
              error:
                type: string
              message:
                type: string
                default: The account already exits.
        500:
          description: Internal server error indicating a fatal error.
          schema:
            $ref: "#/definitions/InternalServerError"

  /accounts/{account_no}:
    delete:
      description: |
        Deletes an account.
      security:
        - AuthToken: []
      parameters:
        - name: account_no
          in: path
          type: string
          required: true
          description: Identifies the account to be deleted.
      responses:
        200:
          description: Successfully deleted the account.
          schema:
            properties:
              message:
                type: string
                default: The account was successfully deleted.
        404:
          description: The account with the given account number could not be found.
          schema:
            properties:
              error:
                type: string
              message:
                type: string
                default: The account does not exist.
        500:
          description: Internal server error indicating a fatal error.
          schema:
            $ref: "#/definitions/InternalServerError"

definitions:
  InternalServerError:
    type: object
    required:
      - error
      - message
    properties:
      error:
        type: string
        default: INTERNAL_SERVER_ERROR
      message:
        type: string
        default: Something went wrong. Please try again later.

